CREATE TABLE sales (
         sale_id INT PRIMARY KEY, 
         product_id INT, 
         revenue DECIMAL(10, 2), 
         sale_date DATE
     );
     CREATE TABLE products (
         product_id INT PRIMARY KEY, 
         product_name VARCHAR(100), 
         category VARCHAR(50)
     );
     INSERT INTO products VALUES 
         (1, 'Smartphone', 'Electronics'), 
         (2, 'Laptop', 'Electronics'), 
         (3, 'Refrigerator', 'Appliances');
     INSERT INTO sales VALUES 
         (1, 1, 50000.00, '2023-05-10'), 
         (2, 2, 75000.00, '2023-06-15'), 
         (3, 3, 30000.00, '2023-07-20');


SELECT * FROM PRODUCTS
SELECT * FROM SALES

/*
Find the total revenue generated by each product category in the last year.
*/

SELECT P.CATEGORY,
       SUM(S.REVENUE) AS TOTAL_REVENUE
FROM PRODUCTS P
JOIN SALES S
ON P.PRODUCT_ID = S.PRODUCT_ID
WHERE SALE_DATE >=  CURRENT_DATE - INTERVAL '1 Year'
GROUP BY 1
